export const AUTH = {
  INIT_DATA: "AUTH_INIT_DATA",
};

export const HOME_PAGE = {
  INIT_DATA: "HOME_PAGE_INIT_DATA",
};

export const ACTION_TYPE = {
  INIT_DATA: "AUTH_INIT_DATA",
  CURRENT_USER: "CURRENT_USER",
  ACCESSTOKEN: "ACCESSTOKEN",
  RESET_ACCESSTOKEN: "RESET_ACCESSTOKEN",

  GET_LIST_ALLOWANCES: "GET_LIST_ALLOWANCES",
  GET_LIST_ALLOWANCES_REFRESH: "GET_LIST_ALLOWANCES_REFRESH",
  SET_LIST_ALLOWANCES_EMPTY: "SET_LIST_ALLOWANCES_EMPTY",

  GET_LIST_JOB_TITLE: "GET_LIST_JOB_TITLE",
  GET_LIST_JOB_TITLE_REFRESH: "GET_LIST_JOB_TITLE_REFRESH",
  GET_OPTION_JOB_TITLE: "GET_OPTION_JOB_TITLE",
  SET_LIST_JOB_TITLE_EMPTY: "SET_LIST_JOB_TITLE_EMPTY",

  GET_LIST_INSURANCE: "GET_LIST_INSURANCE",
  GET_LIST_INSURANCE_REFRESH: "GET_LIST_INSURANCE_REFRESH",
  SET_LIST_INSURANCE_EMPTY: "SET_LIST_INSURANCE_EMPTY",

  GET_LIST_TIMEKEEPER: "GET_LIST_TIMEKEEPER",
  GET_LIST_TIMEKEEPER_REFRESH: "GET_LIST_TIMEKEEPER_REFRESH",
  SET_LIST_TIMEKEEPER_EMPTY: "SET_LIST_TIMEKEEPER_EMPTY",

  GET_LIST_LEVEL: "GET_LIST_LEVEL",
  GET_LIST_LEVEL_REFRESH: "GET_LIST_LEVEL_REFRESH",
  GET_OPTION_LEVEL: "GET_OPTION_LEVEL",
  SET_LIST_LEVEL_EMPTY: "SET_LIST_LEVEL_EMPTY",

  GET_LIST_DEPARTMENT: "GET_LIST_DEPARTMENT",
  GET_LIST_DEPARTMENT_REFRESH: "GET_LIST_DEPARTMENT_REFRESH",
  GET_OPTION_DEPARTMENT: "GET_OPTION_DEPARTMENT",
  SET_LIST_DEPARTMENT_EMPTY: "SET_LIST_DEPARTMENT_EMPTY",

  GET_LIST_SHIFT: "GET_LIST_SHIFT",
  GET_LIST_SHIFT_REFRESH: "GET_LIST_SHIFT_REFRESH",
  GET_OPTION_SHIFT: "GET_OPTION_SHIFT",
  SET_LIST_SHIFT_EMPTY: "SET_LIST_SHIFT_EMPTY",

  GET_LIST_HOLIDAY: "GET_LIST_HOLIDAY",
  GET_LIST_HOLIDAY_REFRESH: "GET_LIST_HOLIDAY_REFRESH",
  SET_LIST_HOLIDAY_EMPTY: "SET_LIST_HOLIDAY_EMPTY",

  GET_LIST_CONTRACT: "GET_LIST_CONTRACT",
  GET_LIST_CONTRACT_REFRESH: "GET_LIST_CONTRACT_REFRESH",
  GET_LIST_CONTRACT_DETAIL: "GET_LIST_CONTRACT_DETAIL",
  GET_LIST_CONTRACT_DETAIL_REFRESH: "GET_LIST_CONTRACT_DETAIL_REFRESH",
  GET_OPTION_CONTRACT: "GET_OPTION_CONTRACT",
  SET_LIST_CONTRACT_EMPTY: "SET_LIST_CONTRACT_EMPTY",

  GET_LIST_DETAIL_CONTRACT: "GET_LIST_DETAIL_CONTRACT",
  GET_LIST_DETAIL_CONTRACT_REFRESH: "GET_LIST_DETAIL_CONTRACT_REFRESH",

  GET_LIST_EMPLOYEE: "GET_LIST_EMPLOYEE",
  GET_LIST_EMPLOYEE_REFRESH: "GET_LIST_EMPLOYEE_REFRESH",
  GET_LIST_EMPLOYEE_INACTIVE: "GET_LIST_EMPLOYEE_INACTIVE",
  GET_LIST_EMPLOYEE_INACTIVE_REFRESH: "GET_LIST_EMPLOYEE_INACTIVE_REFRESH",
  SET_LIST_EMPLOYEE_EMPTY: "SET_LIST_EMPLOYEE_EMPTY",

  GET_LIST_PERSON_TAX: "GET_LIST_PERSON_TAX",
  GET_LIST_PERSON_TAX_REFRESH: "GET_LIST_PERSON_TAX_REFRESH",
  SET_LIST_PERSON_TAX_EMPTY: "SET_LIST_PERSON_TAX_EMPTY",

  GET_LIST_KIND_OF_OVERTIME: "GET_LIST_KIND_OF_OVERTIME",
  GET_LIST_KIND_OF_OVERTIME_REFRESH: "GET_LIST_KIND_OF_OVERTIME_REFRESH",
  SET_LIST_KIND_OF_OVERTIME_EMPTY: "SET_LIST_KIND_OF_OVERTIME_EMPTY",

  GET_LIST_DECLARE_OVERTIME: "GET_LIST_DECLARE_OVERTIME",
  GET_LIST_DECLARE_OVERTIME_REFRESH: "GET_LIST_DECLARE_OVERTIME_REFRESH",
  SET_LIST_DECLARE_OVERTIME_EMPTY: "SET_LIST_DECLARE_OVERTIME_EMPTY",

  GET_LIST_TIMESHEET: "GET_LIST_TIMESHEET",
  GET_LIST_TIMESHEET_REFRESH: "GET_LIST_TIMESHEET_REFRESH",

  GET_LIST_TIMEKEEPING: "GET_LIST_TIMEKEEPING",
  GET_LIST_TIMEKEEPING_REFRESH: "GET_LIST_TIMEKEEPING_REFRESH",

  GET_LIST_ROLE: "GET_LIST_ROLE",
  GET_LIST_ROLE_REFRESH: "GET_LIST_ROLE_REFRESH",

  GET_LIST_LEAVE_DECLARE: "GET_LIST_LEAVE_DECLARE",
  GET_LIST_LEAVE_DECLARE_REFRESH: "GET_LIST_LEAVE_DECLARE_REFRESH",

  GET_LIST_SALARY_CAL: "GET_LIST_SALARY_CAL",
  GET_LIST_SALARY_CAL_REFRESH: "GET_LIST_SALARY_CAL_REFRESH",

  GET_LIST_DETAIL_SALARY_CAL: "GET_LIST_DETAIL_SALARY_CAL",
  GET_LIST_DETAIL_SALARY_CAL_REFRESH: "GET_LIST_DETAIL_SALARY_CAL_REFRESH",
};
