const SCREEN_NAME = {
  LOGIN_SCREEN: "LOGIN_SCREEN",
  TIMEKEEPING: "TIMEKEEPING",
  EMPLOYEE: "EMPLOYEE",
  DEV_SCREEN: "DEV_SCREEN",
  // Bottom Tab
  HOME_SCREEN_STACK: "HOME_SCREEN_STACK",
  NOTIFICATION_SCREEN_STACK: "NOTIFICATION_SCREEN_STACK",
  MANAGE_SCREEN_STACK: "MANAGE_SCREEN_STACK",
  PERSON_SCREEN_STACK: "PERSON_SCREEN_STACK",

  // Screen
  HOME_SCREEN: "HOME_SCREEN",
  NOTIFICATION_SCREEN: "NOTIFICATION_SCREEN",
  MANAGE_SCREEN: "MANAGE_SCREEN",
  PERSON_SCREEN: "PERSON_SCREEN",

  MANAGE_CATEGORY: "MANAGE_CATEGORY",
  CONTRACT_CATEGORY: "CONTRACT_CATEGORY",
  // Allowance
  ALLOWANCE_SCREEN: "ALLOWANCE_SCREEN",
  ALLOWANCE_CREATE_SCREEN: "ALLOWANCE_CREATE_SCREEN",
  ALLOWANCE_EDIT_SCREEN: "ALLOWANCE_EDIT_SCREEN",

  // Job Title
  JOB_TITLE_SCREEN: "JOB_TITLE_SCREEN",
  JOB_TITLE_CREATE_SCREEN: "JOB_TITLE_CREATE_SCREEN",
  JOB_TITLE_EDIT_SCREEN: "JOB_TITLE_EDIT_SCREEN",

  // Holiday
  HOLIDAY_SCREEN: "HOLIDAY_SCREEN",
  HOLIDAY_CREATE_SCREEN: "HOLIDAY_CREATE_SCREEN",
  HOLIDAY_EDIT_SCREEN: "HOLIDAY_EDIT_SCREEN",

  // Timekeeper
  TIMEKEEPER_SCREEN: "TIMEKEEPER_SCREEN",
  TIMEKEEPER_CREATE_SCREEN: "TIMEKEEPER_CREATE_SCREEN",
  TIMEKEEPER_EDIT_SCREEN: "TIMEKEEPER_EDIT_SCREEN",
  // Insurance
  INSURANCE_SCREEN: "INSURANCE_SCREEN",
  INSURANCE_CREATE_SCREEN: "INSURANCE_CREATE_SCREEN",
  INSURANCE_EDIT_SCREEN: "INSURANCE_EDIT_SCREEN",
  // Level
  LEVEL_SCREEN: "LEVEL_SCREEN",
  LEVEL_CREATE_SCREEN: "LEVEL_CREATE_SCREEN",
  LEVEL_EDIT_SCREEN: "LEVEL_EDIT_SCREEN",
  // Department
  DEPARTMENT_SCREEN: "DEPARTMENT_SCREEN",
  DEPARTMENT_CREATE_SCREEN: "DEPARTMENT_CREATE_SCREEN",
  DEPARTMENT_EDIT_SCREEN: "DEPARTMENT_EDIT_SCREEN",
  // Shift
  SHIFT_SCREEN: "SHIFT_SCREEN",
  SHIFT_CREATE_SCREEN: "SHIFT_CREATE_SCREEN",
  SHIFT_EDIT_SCREEN: "SHIFT_EDIT_SCREEN",
  // Contract
  CONTRACT_SCREEN: "CONTRACT_SCREEN",
  CONTRACT_CREATE_SCREEN: "CONTRACT_CREATE_SCREEN",
  CONTRACT_EDIT_SCREEN: "CONTRACT_EDIT_SCREEN",
  // Contract
  CONTRACT_DETAIL_SCREEN: "CONTRACT_DETAIL_SCREEN",
  CONTRACT_CREATE_SCREEN: "CONTRACT_CREATE_SCREEN",
  CONTRACT_EDIT_SCREEN: "CONTRACT_EDIT_SCREEN",
  // Employee
  EMPLOYEE_SCREEN: "EMPLOYEE_SCREEN",
  EMPLOYEE_CREATE_SCREEN: "EMPLOYEE_CREATE_SCREEN",
  EMPLOYEE_EDIT_SCREEN: "EMPLOYEE_EDIT_SCREEN",
  EMPLOYEE_INACTIVE_SCREEN: "EMPLOYEE_INACTIVE_SCREEN",

  // SALARY
  SALARY_CATEGORY_SCREEN: "SALARY_CATEGORY_SCREEN",

  // Person Tax
  PERSON_TAX_SCREEN: "PERSON_TAX_SCREEN",
  PERSON_TAX_CREATE_SCREEN: "PERSON_TAX_CREATE_SCREEN",
  PERSON_TAX_EDIT_SCREEN: "PERSON_TAX_EDIT_SCREEN",

  // Person Tax
  ROLE_SCREEN: "ROLE_SCREEN",
  ROLE_CREATE_SCREEN: "ROLE_CREATE_SCREEN",
  ROLE_EDIT_SCREEN: "ROLE_EDIT_SCREEN",

  // Kind of Over Time
  KIND_OF_OVERTIME_SCREEN: "KIND_OF_OVERTIME_SCREEN",
  KIND_OF_OVERTIME_CREATE_SCREEN: "KIND_OF_OVERTIME_CREATE_SCREEN",
  KIND_OF_OVERTIME_EDIT_SCREEN: "KIND_OF_OVERTIME_EDIT_SCREEN",
  // Declare Over Time
  DECLARE_OVERTIME_SCREEN: "DECLARE_OVERTIME_SCREEN",
  DECLARE_OVERTIME_CREATE_SCREEN: "DECLARE_OVERTIME_CREATE_SCREEN",
  DECLARE_OVERTIME_EDIT_SCREEN: "DECLARE_OVERTIME_EDIT_SCREEN",

  TIMESHEETS_SCREEN: "TIMESHEETS_SCREEN",
  TIMEKEEPING_HISTORY_SCREEN: "TIMEKEEPING_HISTORY_SCREEN",

  LEAVE_SCREEN: "LEAVE_SCREEN",
  LEAVE_CREATE_SCREEN: "LEAVE_CREATE_SCREEN",

  PAYROLL_SCREEN: "PAYROLL_SCREEN",
  INCOME_CREATE_SCREEN: "INCOME_CREATE_SCREEN",

  SALARY_CAL_SCREEN: "SALARY_CAL_SCREEN",
  DETAIL_SALARY_SCREEN: "DETAIL_SALARY_SCREEN",
  DETAIL_SALARY_EMPLOYEE_SCREEN: "DETAIL_SALARY_EMPLOYEE_SCREEN",
  SALARY_CAL_CREATE_SCREEN: "SALARY_CAL_CREATE_SCREEN",
  CHANGE_PASSWORD_SCREEN: "CHANGE_PASSWORD_SCREEN",

  CONTRACT_DETAIL_SCREEN: "CONTRACT_DETAIL_SCREEN",
  CONTRACT_DETAIL_CREATE_SCREEN: "CONTRACT_DETAIL_CREATE_SCREEN",
  EMPLOYEE_PICK_SCREEN: "EMPLOYEE_PICK_SCREEN",
};
export default SCREEN_NAME;
